# .github/workflows/build-dynamic-dotnet6.yml
name: Build Only Changed Console Apps (.NET 6)

on:
  push:
  pull_request:

jobs:
  detect:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ConsoleApp1:
              - 'ConsoleApp1/**'
            ConsoleApp4:
              - 'ConsoleApp4/**'

  build:
    needs: detect
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.detect.outputs.apps) }}
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # sets SDK version to .NET 6 :contentReference[oaicite:1]{index=1}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build ${{ matrix.app }}
        run: dotnet build --configuration Release
