# .github/workflows/build-dynamic-dotnet6.yml

name: Build Only Changed Console Apps (.NET 6)

on:
  push:
  pull_request:

jobs:
  detect:
    runs-on: ubuntu-latest
    permissions: pull-requests: read
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ConsoleApp1:
              - 'ConsoleApp1/**'
            ConsoleApp4:
              - 'ConsoleApp4/**'
          list-files: 'json'

  build:
    needs: detect
    runs-on: ubuntu-latest
    if: ${{ needs.detect.outputs.apps != '[]' && needs.detect.outputs.apps != '' }}
    strategy:
      matrix:
        app: ${{ fromJson(needs.detect.outputs.apps) }}
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build ${{ matrix.app }}
        run: dotnet build --configuration Release
