# .github/workflows/build-and-publish.yml
name: Build and Publish Artifacts

on:
  push:
    paths:
      - 'ConsoleApp1/**'
      - 'ConsoleApp4/**'

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ConsoleApp1:
              - 'ConsoleApp1/**'
            ConsoleApp4:
              - 'ConsoleApp4/**'
          list-files: 'json'

  build:
    needs: detect_changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.apps != '[]' && needs.detect_changes.outputs.apps != '' }}
    strategy:
      matrix:
        app: ${{ fromJson(needs.detect_changes.outputs.apps) }}
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build ${{ matrix.app }}
        run: dotnet build --configuration Release

  publish_artifact:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-build
          path: |
            ConsoleApp1/bin/Release/net6.0/
            ConsoleApp4/bin/Release/net6.0/
