name: Windows Self-Hosted Runner with Windows PowerShell

on: [push]


jobs:
  test:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell  # 👈 Explicitly use Windows PowerShell
    steps:
      - name: Say Hello
        run: echo "✅ Running on Windows self-hosted runner using Windows PowerShell!"


