name: Windows Self-Hosted Workflow

on:
  push:
    branches: [ main ]

jobs:
  windows-job:
    name: Run on Windows Self-Hosted Runner
    runs-on: self-hosted
    # Optionally specify OS if multiple runners
    # labels are registered: runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set PowerShell Execution Policy
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        shell: pwsh

      - name: Run PowerShell Script
        run: echo "Running on Windows self-hosted runner!"
        shell: pwsh

