name: Build and Package

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'
  OUTPUT_PATH: 'bin/Release/net6.0'

jobs:
  build-and-package:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            consoleapp1:
              - 'ConsoleApp1/**'
            consoleapp2:
              - 'ConsoleApp4/**'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build ConsoleApp1
        if: steps.changes.outputs.consoleapp1 == 'true'
        run: dotnet build ConsoleApp1/ConsoleApp1.csproj --configuration Release --no-restore

      - name: Build ConsoleApp2
        if: steps.changes.outputs.consoleapp2 == 'true'
        run: dotnet build ConsoleApp4/ConsoleApp4.csproj --configuration Release --no-restore

      

      - name: Publish ConsoleApp1
        if: steps.changes.outputs.consoleapp1 == 'true'
        run: dotnet publish ConsoleApp1/ConsoleApp1.csproj --configuration Release --output ${{ env.OUTPUT_PATH }}

      - name: Publish ConsoleApp2
        if: steps.changes.outputs.consoleapp2 == 'true'
        run: dotnet publish ConsoleApp2/ConsoleApp2.csproj --configuration Release --output ${{ env.OUTPUT_PATH }}

      - name: Upload ConsoleApp1 artifact
        if: steps.changes.outputs.consoleapp1 == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: consoleapp1-build
          path: ${{ env.OUTPUT_PATH }}
          retention-days: 7

      - name: Upload ConsoleApp2 artifact
        if: steps.changes.outputs.consoleapp2 == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: consoleapp2-build
          path: ${{ env.OUTPUT_PATH }}
          retention-days: 7
